In [1]:
pip install numpy

SyntaxError: invalid syntax (<ipython-input-1-18ba4e71f9fb>, line 1)

In [4]:
import numpy as np

In [4]:
a = np.array([1,2,3])

In [5]:
a


array([1, 2, 3])

In [6]:
a.shape

(3,)

In [8]:
a.reshape(3,1)

array([[1],
       [2],
       [3]])

In [9]:
np.arange(0,100)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [3]:
import pandas as pd

In [5]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4),index = ['1','2','3','4','5'])

In [13]:
df

0   1   2   3
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15
5  16  17  18  19

In [14]:
df.to_csv()

',0,1,2,3\n1,0,1,2,3\n2,4,5,6,7\n3,8,9,10,11\n4,12,13,14,15\n5,16,17,18,19\n'

In [15]:
#3 important things
#Data, Index names and Column names
#Accessing the elements
'''
1. .loc (row location)
2. .iloc (row and column location)
'''

In [18]:
df.loc['2']

0    4
1    5
2    6
3    7
Name: 2, dtype: int64

In [19]:
df.iloc[0:3,0:3]

0  1   2
1  0  1   2
2  4  5   6
3  8  9  10

In [20]:
#Python index starts from 0
#R index starts from 1

In [23]:
b = df.iloc[0:3,0:0]

In [27]:
b


Empty DataFrame
Columns: []
Index: [1, 2, 3]

In [28]:
type(b)

pandas.core.frame.DataFrame

In [29]:
c = df.iloc[0:3,0]

In [30]:
c


1    0
2    4
3    8
Name: 0, dtype: int64

In [31]:
type(c)

pandas.core.series.Series

In [32]:
df

0   1   2   3
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15
5  16  17  18  19

In [34]:
df.values #converting dataframe to arrays

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [35]:
#how to check null condition 
df.isnull()

0      1      2      3
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
5  False  False  False  False

In [36]:
df.isnull().sum()

0    0
1    0
2    0
3    0
dtype: int64

In [6]:
#count function
#Unique function
df['1'].unique()

KeyError: '1'